### ISSUE TITLE
主程序无法启动

### ISSUE THREAD

**Issue by TokamakYuri** [latorc/MahjongCopilot#22]
主程序偶然会发生无法初始化的问题，一旦出现无法初始化的问题接下去如何操作均无法再次正常启动主程序

> 2024-04-21 10:54:41,265 INFO [MainThread]settings.py:65 | Settings initialized and saved to settings.json
2024-04-21 10:54:41,622 INFO [BotThread]bot_manager.py:221 | Starting mitm proxy server, port=10999, upstream_proxy=sock5://localhost:7890
2024-04-21 10:54:41,622 INFO [BotThread]bot_manager.py:223 | Installing MITM certificate
2024-04-21 10:54:41,632 DEBUG [BotThread]mitm.py:180 | Certificate file: E:\MahjongCopilot\mitm_config\mitmproxy-ca-cert.cer
2024-04-21 10:54:41,665 INFO [UpdateHTML]updater.py:57 | Loading help html from https://mjcopilot.com/help
2024-04-21 10:54:41,726 INFO [BotThread]bot_manager.py:225 | MITM certificate installed
2024-04-21 10:54:41,726 ERROR [BotThread]bot_manager.py:263 | Bot Manager Thread Exception: Event loop is closed
Traceback (most recent call last):
  File "bot_manager.py", line 225, in _run
  File "logging\__init__.py", line 1489, in info
  File "logging\__init__.py", line 1634, in _log
  File "logging\__init__.py", line 1644, in handle
  File "logging\__init__.py", line 1706, in callHandlers
  File "logging\__init__.py", line 978, in handle
  File "mitmproxy\log.py", line 221, in emit
  File "asyncio\base_events.py", line 806, in call_soon_threadsafe
  File "asyncio\base_events.py", line 519, in _check_closed
RuntimeError: Event loop is closed
2024-04-21 10:54:42,546 DEBUG [Check_update]updater.py:105 | Check update: Local version=0.5.5, Web version=0.5.5
2024-04-21 10:54:42,546 ERROR [Check_update]updater.py:113 | Event loop is closed

**Comment by c12597259** [comment]
只能去settings.json里面把upstream_proxy的值改掉了

**Comment by TokamakYuri** [comment]
弄好了，看来确实是设置代理的问题

**Comment by latorc** [comment]
改进了 mitm 出错的错误提示。

**Comment by Zxis233** [comment]
不知道怎么样可以让雀魂走clash的代理。
代理地址设置成`http://127.0.0.1:7890`，一直会报`Event loop is closed`
