### ISSUE TITLE
对局发生错误

### ISSUE THREAD

**Issue by Nuohai-muxi** [latorc/MahjongCopilot#62]
Error processing msg: list index out of range
Traceback (most recent call last):
  File "bot_manager.py", line 267, in _run
  File "bot_manager.py", line 395, in _process_msg
  File "game\game_state.py", line 131, in input
  File "game\game_state.py", line 200, in _input_inner
  File "game\game_state.py", line 416, in ms_action_prototype
  File "game\game_state.py", line 623, in _react_all
  File "bot\bot.py", line 16, in reaction_convert_meta
  File "common\mj_helper.py", line 232, in meta_to_options
IndexError: list index out of range

**Comment by Nuohai-muxi** [comment]
出现在三麻对局中

**Comment by Nuohai-muxi** [comment]
解决了，原来是没加 libriichi3p files
